openapi: 3.0.3
info:
  title: 统计 API
  version: 1.0.0
tags:
  - name: 统计
    description: 统计相关接口
paths:
  /api/erp/sc/data/sales_report/asinDailyLists:
    post:
      tags: [统计]
      summary: 查询销量、订单量、销售额
      description: 支持按Asin或MSKU查询销量、订单量、销售额
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: integer
                  description: 店铺id ，对应查询亚马逊店铺列表接口对应字段【sid】
                  example: 109
                event_date:
                  type: string
                  format: date
                  description: 报表时间【站点时间】，格式：Y-m-d
                  example: "2024-08-05"
                asin_type:
                  type: integer
                  description: 查询维度：【默认1】1 asin 2 msku
                  default: 1
                  example: 1
                type:
                  type: integer
                  description: 类型：【默认1】1 销售额 2 销量 3 订单量
                  default: 1
                  example: 1
                offset:
                  type: integer
                  description: 分页偏移量，默认0
                  default: 0
                  example: 0
                length:
                  type: integer
                  description: 分页长度，默认1000
                  default: 1000
                  example: 1000
              required: [sid, event_date]
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsinDailyListsResponse'

  /api/statistics/order-profit-msku:
    post:
      tags: [统计]
      summary: 订单利润MSKU查询
      description: 查询订单利润-MSKU
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                offset:
                  type: integer
                  description: 分页偏移量，默认0
                length:
                  type: integer
                  description: 分页长度，默认20，上限5000
                sids:
                  type: array
                  items:
                    type: integer
                  description: 店铺id数组
                startDate:
                  type: string
                  format: date
                  description: 查询开始时间
                endDate:
                  type: string
                  format: date
                  description: 查询结束时间
                searchField:
                  type: string
                  description: 搜索值类型，可选值：seller_sku, asin, local_name, local_sku
                searchValue:
                  type: array
                  items:
                    type: string
                  description: 搜索的值，数组
                currencyCode:
                  type: string
                  description: 币种code，可选值：原币种、CNY、USD、EUR、JPY、AUD、CAD、MXN、GBP、INR、AED、SGD、SAR、BRL、SEK、PLN、TRY、HKD
              required: [startDate, endDate]
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderProfitMSKUResponse'

  /api/erp/sc/data/sales_report/sales:
    post:
      tags: [统计]
      summary: 店铺汇总销量查询
      description: 查询店铺汇总销量，支持按店铺维度查询店铺销量、销售额
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: array
                  items:
                    type: integer
                  description: 店铺id数组
                start_date:
                  type: string
                  format: date
                  description: 报表开始时间
                end_date:
                  type: string
                  format: date
                  description: 报表结束时间
                offset:
                  type: integer
                  description: 分页偏移量，默认0
                length:
                  type: integer
                  description: 分页长度，默认1000
              required: [sid, start_date, end_date]
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalesReportShopSummaryResponse'

  /api/bd/productPerformance/openApi/asinList:
    post:
      tags: [统计]
      summary: 查询产品表现
      description: 查询产品表现，调用外部OpenAPI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                offset:
                  type: integer
                  description: 分页偏移量
                length:
                  type: integer
                  description: 分页长度，最大10000
                sort_field:
                  type: string
                  description: 排序字段，可选值：volume, order_items, amount, volume_chain_ratio, order_chain_ratio, amount_chain_ratio, b2b_volume, b2b_order_items, promotion_volume, promotion_amount, promotion_order_items, promotion_discount, avg_volume
                sort_type:
                  type: string
                  description: 排序方式，可选值：desc、asc
                search_field:
                  type: string
                  description: 搜索字段，可选值：asin, parent_asin, msku, local_sku, item_name
                search_value:
                  type: array
                  items:
                    type: string
                  description: 搜索值，最多50个
                mid:
                  type: integer
                  description: 站点id
                sid:
                  oneOf:
                    - type: string
                    - type: array
                      items:
                        type: integer
                  description: 店铺id，上限200
                start_date:
                  type: string
                  format: date
                  description: 开始日期，格式Y-m-d
                end_date:
                  type: string
                  format: date
                  description: 结束日期，格式Y-m-d
                extend_search:
                  type: array
                  items:
                    type: object
                    properties:
                      field:
                        type: string
                        description: 筛选字段
                      from_value:
                        type: integer
                        description: 区间/比较值
                      to_value:
                        type: integer
                        description: 右区间值
                      exp:
                        type: string
                        description: 可取值：range、gt、lt、ge、le、eq
                summary_field:
                  type: string
                  description: 汇总行维度，可选值：asin, parent_asin, msku, sku
                currency_code:
                  type: string
                  description: 货币类型，不传代表原币种，转换仅支持USD、CNY
                is_recently_enum:
                  type: boolean
                  description: 是否仅查询活跃商品，true仅活跃，false全部
                avg_volume:
                  type: string
                  description: 平均销量字段
              required: [offset, length, sort_field, sort_type, sid, start_date, end_date, summary_field, avg_volume]
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPerformanceResponse'

  /api/basicOpen/salesAnalysis/productPerformance/performanceTrendByHour:
    post:
      tags: [统计]
      summary: 查询asin360小时数据
      description: 查询asin360小时数据，调用外部OpenAPI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sids:
                  type: string
                  description: 店铺id，多个值用英文逗号隔开，最大200
                date_start:
                  type: string
                  format: date
                  description: 开始时间，格式Y-m-d
                date_end:
                  type: string
                  format: date
                  description: 结束时间，格式Y-m-d
                summary_field:
                  type: string
                  description: 查询维度，可选值：parent_asin, asin, msku, sku, spu
                summary_field_value:
                  type: string
                  description: 查询维度值
              required: [sids, date_start, date_end, summary_field, summary_field_value]
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPerformanceTrendByHourResponse'

  /api/bd/profit/statistics/open/asin/list:
    post:
      tags: [统计]
      summary: 利润统计-ASIN
      description: 查询利润统计-ASIN，调用外部OpenAPI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                offset:
                  type: integer
                  description: 分页偏移量
                length:
                  type: integer
                  description: 分页长度，上限10000
                mids:
                  type: array
                  items:
                    type: integer
                  description: 站点id
                sids:
                  type: array
                  items:
                    type: integer
                  description: 店铺id
                startDate:
                  type: string
                  format: date
                  description: 开始时间，格式Y-m-d
                endDate:
                  type: string
                  format: date
                  description: 结束时间，格式Y-m-d
                searchField:
                  type: string
                  description: 搜索值类型
                searchValue:
                  type: array
                  items:
                    type: string
                  description: 搜索值
                currencyCode:
                  type: string
                  description: 币种code
              required: [startDate, endDate]
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfitStatisticsAsinListResponse'

components:
  schemas:
    AsinDailyListsResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
    OrderProfitMSKUResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
    SalesReportShopSummaryResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
    ProductPerformanceResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
    ProductPerformanceTrendByHourResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
    ProfitStatisticsAsinListResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object