openapi: 3.0.3
info:
  title: 基础数据 API
  version: 1.0.0
tags:
  - name: 基础数据
    description: 基础数据相关接口

paths:
  /api/erp/sc/routing/finance/currency/currencyMonth:
    post:
      tags: [基础数据]
      summary: 查询汇率
      description: 查询汇率（月度）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                month:
                  type: string
                  format: yyyy-MM
                  description: 月份
                currency_code:
                  type: string
                  description: 币种
              required: [month, currency_code]
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyExchangeRateResponse'

  /api/erp/sc/data/seller/lists:
    get:
      tags: [基础数据]
      summary: 查询亚马逊店铺列表
      description: 查询亚马逊店铺列表
      parameters:
        - in: query
          name: platform
          schema:
            type: string
          description: 平台类型
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmazonSellerListResponse'

  /api/erp/sc/data/seller/allMarketplace:
    get:
      tags: [基础数据]
      summary: 查询亚马逊市场列表
      description: 查询亚马逊市场列表
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmazonMarketplaceListResponse'

  /api/erp/sc/data/worldState/lists:
    post:
      tags: [基础数据]
      summary: 查询世界州/省列表
      description: 查询世界州/省列表
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                country_code:
                  type: string
                  description: 国家代码
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorldStateListResponse'

  /api/erp/sc/routing/common/file/download:
    post:
      tags: [基础数据]
      summary: 下载产品附件
      description: 下载产品附件
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_id:
                  type: string
                  description: 文件ID
              required: [file_id]
      responses:
        '200':
          description: 成功
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /api/erp/sc/routing/customized/file/download:
    post:
      tags: [基础数据]
      summary: 定制化附件下载
      description: 定制化附件下载
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_id:
                  type: string
                  description: 文件ID
              required: [file_id]
      responses:
        '200':
          description: 成功
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /api/erp/sc/data/account/lists:
    get:
      tags: [基础数据]
      summary: 查询ERP用户信息列表
      description: 查询ERP用户信息列表
      parameters:
        - in: query
          name: role
          schema:
            type: string
          description: 用户角色
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErpUserListResponse'

  /api/erp/sc/data/seller/batchEditSellerName:
    post:
      tags: [基础数据]
      summary: 批量修改店铺名称
      description: 批量修改店铺名称
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                seller_names:
                  type: array
                  items:
                    type: object
                    properties:
                      sid:
                        type: integer
                        description: 店铺ID
                      new_name:
                        type: string
                        description: 新店铺名称
              required: [seller_names]
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchEditSellerNameResponse'

components:
  schemas:
    CurrencyExchangeRateResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
    AmazonSellerListResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
    AmazonMarketplaceListResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
    WorldStateListResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
    ErpUserListResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
    BatchEditSellerNameResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object 