openapi: 3.0.3
info:
  title: 未分组 API
  version: 1.0.0
tags:
  - name: 未分组
    description: 未分组接口

paths:
  # 示例：请将所有未分组接口补充到此处
  # 例如：
  # /api/auth/login:
  #   post:
  #     tags: [未分组]
  #     summary: 用户登录
  #     description: 用户登录接口
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               username:
  #                 type: string
  #               password:
  #                 type: string
  #             required: [username, password]
  #     responses:
  #       '200':
  #         description: 成功
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 code:
  #                   type: integer
  #                 message:
  #                   type: string
  #                 data:
  #                   type: object

components:
  schemas:
    # 如有未分组接口用到的响应结构，在此补充
    DefaultResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object 