# API相关常量定义
# 定义API请求、响应相关的常量

# 分页相关常量
DEFAULT_PAGE_SIZE = 1000
MAX_PAGE_SIZE = 5000
DEFAULT_OFFSET = 0

# 超时相关常量
DEFAULT_TIMEOUT = 30  # 秒
LONG_TIMEOUT = 60     # 秒
SHORT_TIMEOUT = 10    # 秒

# HTTP状态码
HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_ERROR = 500
HTTP_BAD_GATEWAY = 502

# 请求头常量
CONTENT_TYPE_JSON = 'application/json'
CONTENT_TYPE_FORM = 'application/x-www-form-urlencoded'
AUTHORIZATION_HEADER = 'Authorization'
USER_AGENT_HEADER = 'User-Agent'

# 默认用户代理
DEFAULT_USER_AGENT = 'RPA-Tornado/1.0'

# 限流相关常量
DEFAULT_RATE_LIMIT_CAPACITY = 10
DEFAULT_RATE_LIMIT_REFILL_RATE = 1.0

# 缓存相关常量
DEFAULT_CACHE_TTL = 300  # 5分钟
LONG_CACHE_TTL = 3600    # 1小时
SHORT_CACHE_TTL = 60     # 1分钟