# 业务常量定义
# 定义业务逻辑相关的常量

# ASIN类型常量
ASIN_TYPE_ASIN = 1  # 按ASIN查询
ASIN_TYPE_MSKU = 2  # 按MSKU查询

# 报表类型常量
REPORT_TYPE_SALES = 1      # 销售额
REPORT_TYPE_QUANTITY = 2   # 销量
REPORT_TYPE_ORDERS = 3     # 订单量

# 店铺状态常量
SELLER_STATUS_ACTIVE = 1     # 活跃
SELLER_STATUS_INACTIVE = 0   # 非活跃
SELLER_STATUS_SUSPENDED = -1 # 暂停

# 产品状态常量
PRODUCT_STATUS_ACTIVE = 1      # 启用
PRODUCT_STATUS_INACTIVE = 0    # 禁用
PRODUCT_STATUS_DELETED = -1    # 已删除

# 平台类型常量
PLATFORM_AMAZON = 'amazon'
PLATFORM_EBAY = 'ebay'
PLATFORM_WALMART = 'walmart'
PLATFORM_SHOPIFY = 'shopify'

# 货币类型常量
CURRENCY_USD = 'USD'
CURRENCY_EUR = 'EUR'
CURRENCY_GBP = 'GBP'
CURRENCY_JPY = 'JPY'
CURRENCY_CNY = 'CNY'

# 市场常量
MARKET_US = 'US'
MARKET_UK = 'UK'
MARKET_DE = 'DE'
MARKET_FR = 'FR'
MARKET_IT = 'IT'
MARKET_ES = 'ES'
MARKET_JP = 'JP'
MARKET_CA = 'CA'
MARKET_AU = 'AU'

# 时间格式常量
DATE_FORMAT = '%Y-%m-%d'
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
TIME_FORMAT = '%H:%M:%S'

# 文件类型常量
FILE_TYPE_EXCEL = 'excel'
FILE_TYPE_CSV = 'csv'
FILE_TYPE_PDF = 'pdf'
FILE_TYPE_JSON = 'json'

# 导出文件大小限制（字节）
MAX_EXPORT_FILE_SIZE = 50 * 1024 * 1024  # 50MB

# 批量操作限制
MAX_BATCH_SIZE = 1000
DEFAULT_BATCH_SIZE = 100

# 重试相关常量
DEFAULT_RETRY_TIMES = 3
DEFAULT_RETRY_DELAY = 1  # 秒
MAX_RETRY_DELAY = 60     # 秒

# 数据有效期常量（天）
DATA_RETENTION_DAYS = 90
LOG_RETENTION_DAYS = 30
TEMP_FILE_RETENTION_HOURS = 24

# 业务规则常量
MIN_PRICE = 0.01
MAX_PRICE = 999999.99
MIN_QUANTITY = 0
MAX_QUANTITY = 999999

# 标签相关常量
MAX_LABEL_LENGTH = 50
MAX_LABELS_PER_PRODUCT = 10

# 图片相关常量
MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5MB
ALLOWED_IMAGE_FORMATS = ['jpg', 'jpeg', 'png', 'gif', 'webp']
MAX_IMAGES_PER_PRODUCT = 10

# API版本常量
API_VERSION_V1 = 'v1'
API_VERSION_V2 = 'v2'
CURRENT_API_VERSION = API_VERSION_V1

# 业务类型映射
ASIN_TYPE_MAPPING = {
    ASIN_TYPE_ASIN: 'ASIN',
    ASIN_TYPE_MSKU: 'MSKU'
}

REPORT_TYPE_MAPPING = {
    REPORT_TYPE_SALES: '销售额',
    REPORT_TYPE_QUANTITY: '销量',
    REPORT_TYPE_ORDERS: '订单量'
}

SELLER_STATUS_MAPPING = {
    SELLER_STATUS_ACTIVE: '活跃',
    SELLER_STATUS_INACTIVE: '非活跃',
    SELLER_STATUS_SUSPENDED: '暂停'
}

PRODUCT_STATUS_MAPPING = {
    PRODUCT_STATUS_ACTIVE: '启用',
    PRODUCT_STATUS_INACTIVE: '禁用',
    PRODUCT_STATUS_DELETED: '已删除'
}